# Generated by Django 4.2.11 on 2024-04-20 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('intro', models.CharField(max_length=500, verbose_name='文章简介')),
                ('category', models.CharField(max_length=100, verbose_name='文章分类')),
                ('content', mdeditor.fields.MDTextField(verbose_name='文章内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='文章作者')),
            ],
        ),
    ]
