# Generated by Django 4.2.11 on 2024-05-02 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('0', '工作报告'), ('1', '项目记录'), ('2', '日程安排')], default='0', max_length=20, verbose_name='分类')),
                ('content', models.TextField(verbose_name='计划内容')),
                ('start_time', models.DateTimeField(default='', verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default='', verbose_name='结束时间')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='report_user', to=settings.AUTH_USER_MODEL, verbose_name='制定者')),
            ],
            options={
                'verbose_name': '工作日报',
                'verbose_name_plural': '工作日报',
            },
        ),
    ]
