# Generated by Django 4.2.11 on 2024-04-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='代理IP')),
                ('type', models.CharField(max_length=20, verbose_name='IP类型')),
                ('validation_time', models.DateTimeField(auto_now_add=True, verbose_name='验证时间')),
            ],
        ),
    ]
