# Generated by Django 4.2.11 on 2024-04-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_proxypool'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxypool',
            name='speed',
            field=models.CharField(default=1, max_length=10, verbose_name='平均速度'),
            preserve_default=False,
        ),
    ]
