# Generated by Django 4.2.11 on 2024-04-20 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_proxypool_speed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProxyPool',
        ),
    ]
