# Generated by Django 4.2.11 on 2024-05-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchplatform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displatform',
            name='task_args',
        ),
    ]
