# Generated by Django 4.2.11 on 2024-05-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchplatform', '0003_alter_displatform_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displatform',
            name='job_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='任务ID'),
        ),
    ]
