# Generated by Django 4.2.11 on 2024-05-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchplatform', '0005_displatform_scheduler_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displatform',
            name='task_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='任务名称'),
        ),
    ]
