# Generated by Django 4.2 on 2024-05-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchplatform', '0006_alter_displatform_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='displatform',
            name='env_variable',
            field=models.CharField(default='', max_length=500, verbose_name='环境变量'),
        ),
    ]
