# Generated by Django 4.2 on 2024-11-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxypool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxypool',
            name='ip',
            field=models.CharField(max_length=50, unique=True, verbose_name='代理IP'),
        ),
    ]
